In [1]:
import numpy as np
import pandas as pd

In [2]:
# df=pd.read_csv("C:\\Users\\subha\\OneDrive\\Documents\\covid_toy.csv")
# df

In [3]:
df=pd.read_csv("C:\\Users\\hp\\Downloads\\cancer patient data sets.csv")
df

,index,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,chronic Lung Disease,Smoking,Chest Pain,Coughing of Blood,Shortness of Breath,Dry Cough,Length Of Stay,Level
0,0,P1,33,1,2,4,5,2,3,2,4,2,3,4,Low
1,1,P10,17,1,3,1,5,2,2,2,3,7,7,2,Medium
2,2,P100,35,1,4,5,6,4,2,4,8,9,7,2,High
3,3,P1000,37,1,7,7,7,7,7,7,8,3,7,5,High
4,4,P101,46,1,6,8,7,6,8,7,9,4,2,3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,P995,44,1,6,7,7,6,7,7,7,2,5,3,High
996,996,P996,37,2,6,8,7,6,7,7,7,5,1,4,High
997,997,P997,25,2,4,5,6,4,2,4,8,9,7,2,High
998,998,P998,18,2,6,8,7,6,8,7,9,4,2,3,High
999,999,P999,47,1,6,5,6,4,2,4,8,9,7,2,High

In [4]:
df1=pd.read_csv("C:\\Users\\hp\\Downloads\\hospital.csv",usecols=["glucose","pulse"])
df1

        glucose  pulse
0    192.476918     96
1     94.078507     61
2    130.530524     64
3    163.377028     76
4     94.886654     67
..          ...    ...
995   99.229834     73
996  215.856429     84
997  178.394463     75
998  192.157665     71
999  124.384981     75

[1000 rows x 2 columns]

In [5]:
df2=np.hstack((df,df1))
df2

# stacked_array = np.hstack((array1, array2))

array([[0, 'P1', 33, ..., 'Low', 192.4769177, 96.0],
       [1, 'P10', 17, ..., 'Medium', 94.07850731, 61.0],
       [2, 'P100', 35, ..., 'High', 130.5305238, 64.0],
       ...,
       [997, 'P997', 25, ..., 'High', 178.3944633, 75.0],
       [998, 'P998', 18, ..., 'High', 192.1576654, 71.0],
       [999, 'P999', 47, ..., 'High', 124.3849813, 75.0]], dtype=object)

In [6]:
df1.columns

Index(['glucose', 'pulse'], dtype='object')

In [7]:
df=pd.DataFrame(df2,columns=['index', 'Patient Id', 'Age', 'Gender', 'Air Pollution', 'Alcohol use',
       'Dust Allergy', 'chronic Lung Disease', 'Smoking', 'Chest Pain',
       'Coughing of Blood', 'Shortness of Breath', 'Dry Cough',
       'Length Of Stay', 'Level','glucose', 'pulse'])
df

,index,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,chronic Lung Disease,Smoking,Chest Pain,Coughing of Blood,Shortness of Breath,Dry Cough,Length Of Stay,Level,glucose,pulse
0,0,P1,33,1,2,4,5,2,3,2,4,2,3,4,Low,192.476918,96.0
1,1,P10,17,1,3,1,5,2,2,2,3,7,7,2,Medium,94.078507,61.0
2,2,P100,35,1,4,5,6,4,2,4,8,9,7,2,High,130.530524,64.0
3,3,P1000,37,1,7,7,7,7,7,7,8,3,7,5,High,163.377028,76.0
4,4,P101,46,1,6,8,7,6,8,7,9,4,2,3,High,94.886654,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,P995,44,1,6,7,7,6,7,7,7,2,5,3,High,99.229834,73.0
996,996,P996,37,2,6,8,7,6,7,7,7,5,1,4,High,215.856429,84.0
997,997,P997,25,2,4,5,6,4,2,4,8,9,7,2,High,178.394463,75.0
998,998,P998,18,2,6,8,7,6,8,7,9,4,2,3,High,192.157665,71.0
999,999,P999,47,1,6,5,6,4,2,4,8,9,7,2,High,124.384981,75.0

In [8]:
df = df.drop(columns=['index', 'Patient Id'])
df

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,chronic Lung Disease,Smoking,Chest Pain,Coughing of Blood,Shortness of Breath,Dry Cough,Length Of Stay,Level,glucose,pulse
0,33,1,2,4,5,2,3,2,4,2,3,4,Low,192.476918,96.0
1,17,1,3,1,5,2,2,2,3,7,7,2,Medium,94.078507,61.0
2,35,1,4,5,6,4,2,4,8,9,7,2,High,130.530524,64.0
3,37,1,7,7,7,7,7,7,8,3,7,5,High,163.377028,76.0
4,46,1,6,8,7,6,8,7,9,4,2,3,High,94.886654,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44,1,6,7,7,6,7,7,7,2,5,3,High,99.229834,73.0
996,37,2,6,8,7,6,7,7,7,5,1,4,High,215.856429,84.0
997,25,2,4,5,6,4,2,4,8,9,7,2,High,178.394463,75.0
998,18,2,6,8,7,6,8,7,9,4,2,3,High,192.157665,71.0
999,47,1,6,5,6,4,2,4,8,9,7,2,High,124.384981,75.0

In [9]:
df.isnull().sum()

Age                     0
Gender                  0
Air Pollution           0
Alcohol use             0
Dust Allergy            0
chronic Lung Disease    0
Smoking                 0
Chest Pain              0
Coughing of Blood       0
Shortness of Breath     0
Dry Cough               0
Length Of Stay          0
Level                   0
glucose                 0
pulse                   0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x = df.drop(columns = ['Level'])
y=df['Level']

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [14]:
lb = LabelEncoder()
y_train_label = lb.fit_transform( y_train)
y_train_label
y_test_label = lb.fit_transform( y_test)
y_test_label

array([2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 0, 1, 0, 0, 0, 0, 2,
       1, 2, 0, 1, 2, 0, 1, 1, 1, 0, 2, 1, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2,
       2, 1, 1, 2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 1, 2,
       0, 0, 2, 0, 0, 1, 2, 2, 2, 2, 0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 0, 1,
       0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 1, 2, 0, 0, 2, 2, 2,
       2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 1, 2,
       1, 0, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0,
       2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 0, 2, 1, 2, 1, 1, 2, 0, 0, 2, 0, 0,
       1, 2])

In [15]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import PolynomialFeatures 
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier 
from sklearn import svm

In [16]:
linear = LinearRegression()

In [17]:
linear.fit(x_train , y_train_label)
y_pred = linear.predict(x_test)
y_pred

array([ 1.57463116,  1.8115326 ,  1.51849601, -0.2016979 ,  2.08370905,
        0.85924333,  1.75853328,  2.06553493,  1.57644322,  1.79809047,
        1.8173428 ,  1.37468985,  1.72441613,  1.53242954,  0.73755567,
        0.85799946,  0.98652965,  0.06708342, -0.08305363,  0.16244132,
       -0.21838934,  1.58717356,  1.3572202 ,  1.84088299,  0.35483605,
        1.40442441,  1.84403018,  0.55629021,  1.23977029,  1.40749766,
        0.74251795,  0.61511558,  1.51646761,  0.57870662,  0.70097139,
        0.24248439,  0.49547044,  1.99586473, -0.1576806 ,  1.33141376,
        0.0573033 ,  0.08835209,  1.4535785 ,  1.60436074,  1.54296878,
        0.55478319,  1.24704683,  1.94267068,  0.06750498,  0.77799386,
        0.45019393,  0.28692047,  1.46269559,  0.13172115,  0.07866225,
        0.31776655,  0.70423735,  0.23390545, -0.20730894,  1.47287929,
        1.50805214,  0.80890454,  0.53455602,  0.4964121 ,  1.50904212,
        1.8800447 ,  0.21418994,  0.6863009 ,  1.65203153,  0.37316407,
        0.26013226,  1.55603829,  1.49257914,  1.94047244,  1.62471857,
        1.49883004,  0.18072551,  1.44331435,  1.77050159,  1.52796353,
        1.86133228,  1.4309564 ,  1.61087788,  1.45776268,  0.06927548,
       -0.04880899, -0.17857917,  1.49815939,  0.24302496, -0.22159039,
        1.43338615,  1.797088  ,  2.07020394,  0.2365855 ,  0.27330035,
       -0.24322132,  0.54027671,  0.65094073,  1.52912549,  1.51795555,
        0.77968202,  0.09483045,  1.51129593,  1.82563746,  1.60430695,
        0.66642223, -0.19956925,  1.78505858,  1.40706394,  1.96785789,
        1.35441473,  0.09625851,  0.12634951,  1.45889822,  1.58165908,
        0.5359163 ,  1.4586221 , -0.38261021,  2.03727122,  1.87695672,
       -0.15060608,  0.53877724,  1.44404422,  1.3033247 ,  0.46407406,
       -0.11591313,  0.62063998,  0.27977266,  0.26933696,  0.16971338,
        1.08740062,  1.85805363,  1.44031851,  0.22701296,  1.53134525,
        0.52977404,  1.70875909, -0.03863255,  1.78630127,  1.87055381,
        1.13559733,  1.79165895,  0.52193654,  1.4542997 ,  0.37734535,
        1.90649131,  1.47408177,  0.19504817,  1.80933642,  0.38979629,
        0.66167045,  1.4020762 ,  1.96958843,  0.0714743 ,  1.56329966,
        0.09090611,  0.26736836,  0.96392815,  0.71232283,  0.2535708 ,
        1.87697687,  0.41422002,  0.2005748 , -0.07263279,  0.61655263,
        1.56599425,  1.3388361 ,  0.14838971,  0.39684196,  0.68429335,
        0.56604693,  1.57862577, -0.17278296, -0.14303835,  1.27259603,
        0.33513681,  1.39939704,  0.71333125,  1.77798025,  0.84591319,
        0.77690892, -0.14380442,  1.05887735,  1.6043122 ,  0.31192093,
        1.88378971,  0.20083171,  1.42837801,  0.8291432 ,  1.83773889,
        0.77846984,  0.26139907,  1.67597943,  0.67121044,  0.27973004,
        1.94983878, -0.1864584 ,  0.13388949,  0.94560004,  2.06945123])

In [18]:
from sklearn.metrics import r2_score

In [19]:
r2_score(y_test_label, y_pred)

0.7348976708966981

# logisticregression

In [20]:
lg = LogisticRegression()

In [21]:
lg.fit(x_train, y_train_label)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [22]:
y_pred = lg.predict(x_test)
y_pred

array([2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 0, 0, 0, 0, 2,
       1, 2, 0, 1, 1, 0, 1, 1, 1, 0, 2, 1, 0, 0, 0, 2, 0, 1, 0, 0, 2, 2,
       2, 1, 1, 2, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 0, 0, 1, 2, 2, 1, 2, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 1,
       0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 2, 2, 0, 0, 2, 2, 2,
       2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 2,
       1, 0, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 0, 1, 2, 0,
       1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0,
       2, 0, 2, 2, 1, 0, 1, 2, 0, 2, 0, 2, 1, 2, 1, 1, 2, 0, 0, 2, 0, 0,
       1, 2])

In [23]:
r2_score(y_test_label, y_pred)

0.7276441216522923

# decisiontree

In [24]:
dt = DecisionTreeClassifier()

In [25]:
dt.fit(x_train, y_train_label)

DecisionTreeClassifier()

In [26]:
y_pred = dt.predict(x_test)
y_pred

array([2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 0, 1, 0, 0, 0, 0, 2,
       1, 2, 0, 1, 2, 0, 1, 1, 1, 0, 2, 1, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2,
       2, 1, 1, 2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 1, 2,
       0, 0, 2, 0, 0, 1, 2, 2, 2, 2, 0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 0, 1,
       0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 1, 2, 0, 0, 2, 2, 2,
       2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 1, 2,
       1, 0, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0,
       2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 0, 2, 1, 2, 1, 1, 2, 0, 0, 2, 0, 0,
       1, 2])

In [27]:
r2_score( y_test_label, y_pred)

1.0

In [28]:
x_train.head(3)

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,chronic Lung Disease,Smoking,Chest Pain,Coughing of Blood,Shortness of Breath,Dry Cough,Length Of Stay,glucose,pulse
29,28,2,1,6,7,2,3,2,2,7,7,5,190.059466,66.0
535,53,1,6,8,7,7,8,9,6,5,7,6,180.065703,88.0
695,28,2,1,6,7,2,3,2,2,7,7,5,158.415834,88.0

In [ ]:
Age=int(input("entr Age:"))
Gender=int(input("entr gender:"))
AirPollution=int(input("entr airpollution:"))
Alcoholuse=int(input("entr Alcoholuse:"))
DustAllergy=int(input("entr dustallergy:"))
chronicLungDisease=int(input("entr lingdis:"))
Smoking=int(input("entr smoking:"))
ChestPain=int(input("entr chestpain:"))
CoughingofBlood=int(input("entr coughingofblood:"))
ShortnessofBreath=int(input("entr shortnessofbreath:"))
DryCough=int(input("entr drycough:"))
LengthOfStay=int(input("entr lenghtofstay:"))
# Level=int(input("entr Age:"))
glucose=int(input("entr glucose:"))
pulse=int(input("entr pulse:"))

In [ ]:
new_list = np.array([[Age, Gender,AirPollution, Alcoholuse, DustAllergy,
       chronicLungDisease, Smoking, ChestPain, CoughingofBlood,
       ShortnessofBreath, DryCough, LengthOfStay,
       glucose, pulse]])

print(len([Age, Gender,AirPollution, Alcoholuse, DustAllergy,
       chronicLungDisease, Smoking, ChestPain, CoughingofBlood,
       ShortnessofBreath, DryCough, LengthOfStay, Level,
       glucose, pulse]))

In [ ]:
linear.predict(new_list)